apiVersion: v1
kind: ConfigMap
metadata:
  name: habit-tracker-config
  namespace: habit-tracker
data:
  FLASK_DEBUG: "false"
  FLASK_PORT: "5000"
  FLASK_ENV: "production"
  
  DB_NAME: "habit_tracker"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  
  APP_NAME: "Habit racker"
  TIMEZONE: "UTC"
  LOG_LEVEL: "INFO"